# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a763244eec0a67605072c7aa6d6575b23337010ebf0a2acd09e9f6a209b155a1bccc977a156a1b8173c036027adaa3afccc7cc0cc76da4f4e1be49405543199

test:
  secret_key_base: cf263e45c85576ca2f1a43c47b27c658691093125972fd890f4851ec783cb6ba043eeb2a4abd7eb2b03e62ab6b2caf4c3840b1ffccfe3bacc5dcab0caea578a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
